# Generated by Django 4.0.3 on 2022-04-08 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('deleteDate', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=10000)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('image', models.URLField(null=True)),
                ('idAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
