# Generated by Django 4.0.3 on 2022-04-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
